const nahard = {
    "name":"network analysis signals and system",
    "questions": [

        {
            "id":"1",
            "question":"https://i.postimg.cc/RhkWWtSd/1.png",
            "answer":"a"
        },
        {
            "id":"2",
            "question":"https://i.postimg.cc/DfHJj9rG/2.png",
            "answer":"a"
        },
        {
            "id":"3",
            "question":"https://i.postimg.cc/X75ZTsLz/3.png",
            "answer":"c"
        },
        {
            "id":"4",
            "question":"https://i.postimg.cc/N0s52Bc3/4.png",
            "answer":"b"
        },
        {
            "id":"5",
            "question":"https://i.postimg.cc/B6tbNptN/5.png",
            "answer":"a"
        },
        {
            "id":"6",
            "question":"https://i.postimg.cc/W16d4tQm/6.png",
            "answer":"d"
        },
        {
            "id":"7",
            "question":"https://i.postimg.cc/2SfqmnX8/7.png",
            "answer":"b"
        },
        {
            "id":"8",
            "question":"https://i.postimg.cc/DzxmqHf8/8.png",
            "answer":"b"
        },
        {
            "id":"9",
            "question":"https://i.postimg.cc/MT4TLBQw/9.png",
            "answer":"c"
        },
        {
            "id":"10",
            "question":"https://i.postimg.cc/c12XS4y4/10.png",
            "answer":"a"
        },
        {
            "id":"11",
            "question":"https://i.postimg.cc/L51XFst1/11.png",
            "answer":"c"
        },
        {
            "id":"12",
            "question":"https://i.postimg.cc/T2pCF5s4/12.png",
            "answer":"a"
        },
        {
            "id":"13",
            "question":"https://i.postimg.cc/pyMdWtC1/13.png",
            "answer":"c"
        },
        {
            "id":"14",
            "question":"https://i.postimg.cc/65Zz5JtV/14.png",
            "answer":"d"
        },
        {
            "id":"15",
            "question":"https://i.postimg.cc/6QWh08Rz/15.png",
            "answer":"d"
        },
        {
            "id":"16",
            "question":"https://i.postimg.cc/CxHNkGZz/16.png",
            "answer":"b"
        },
        {
            "id":"17",
            "question":"https://i.postimg.cc/FKTVnhVv/17.png",
            "answer":"b"
        },
        {
            "id":"18",
            "question":"https://i.postimg.cc/FRqgNG6n/18.png",
            "answer":"a"
        },
        {
            "id":"19",
            "question":"https://i.postimg.cc/VLXBPqWD/19.png",
            "answer":"d"
        },
        {
            "id":"20",
            "question":"https://i.postimg.cc/fLkjG189/20.png",
            "answer":"b"
        },
        {
            "id":"21",
            "question":"https://i.postimg.cc/jqpQ1gPD/21.png",
            "answer":"a"
        },
        {
            "id":"22",
            "question":"https://i.postimg.cc/VvC96nQs/22.png",
            "answer":"a"
        },
        {
            "id":"23",
            "question":"https://i.postimg.cc/gcXHNFX9/23.png",
            "answer":"b"
        },
        {
            "id":"24",
            "question":"https://i.postimg.cc/pdLDjgb6/24.png",
            "answer":"c"
        },
        {
            "id":"25",
            "question":"https://i.postimg.cc/L8Rk9JyR/25.png",
            "answer":"d"
        },
        {
            "id":"26",
            "question":"https://i.postimg.cc/wjVX79PN/26.png",
            "answer":"b"
        },
        {
            "id":"27",
            "question":"https://i.postimg.cc/bvV193qN/27.png",
            "answer":"d"
        },
        {
            "id":"28",
            "question":"https://i.postimg.cc/76C0s0L1/28.png",
            "answer":"a"
        },
        {
            "id":"29",
            "question":"https://i.postimg.cc/V63M3vSx/29.png",
            "answer":"a"
        },
        {
            "id":"30",
            "question":"https://i.postimg.cc/WzgrjVgh/30.png",
            "answer":"a"
        },
        {
            "id":"31",
            "question":"https://i.postimg.cc/ZYd66824/31.png",
            "answer":"a"
        },
        {
            "id":"32",
            "question":"https://i.postimg.cc/rF2xjd2W/32.png",
            "answer":"b"
        },
        {
            "id":"33",
            "question":"https://i.postimg.cc/gkyRTYG7/33.png",
            "answer":"c"
        },
        {
            "id":"34",
            "question":"https://i.postimg.cc/8z1W8q5z/34.png",
            "answer":"d"
        },
        {
            "id":"35",
            "question":"https://i.postimg.cc/4xBcXB7b/35.png",
            "answer":"c"
        },
        {
            "id":"36",
            "question":"https://i.postimg.cc/Ls515Ljd/36.png",
            "answer":"a"
        },
        {
            "id":"37",
            "question":"https://i.postimg.cc/ZqQydnLW/37.png",
            "answer":"b"
        },
        {
            "id":"38",
            "question":"https://i.postimg.cc/4dhHbG8B/38.png",
            "answer":"d"
        },
        {
            "id":"39",
            "question":"https://i.postimg.cc/DfLbS24z/39.png",
            "answer":"c"
        },
        {
            "id":"40",
            "question":"https://i.postimg.cc/3N54tqV7/40.png",
            "answer":"b"
        },
    ],
};

export default nahard;