const naeasy = {
    "name":"Network Theory ,Signals and System",
    "questions": [

        {
            "id":"1",
            "question":"https://i.postimg.cc/c48Wj18W/1.png",
            "answer":"b"
        },
        {
            "id":"2",
            "question":"https://i.postimg.cc/7Z84yvg2/2.png",
            "answer":"a"
        },
        {
            "id":"3",
            "question":"https://i.postimg.cc/13GQmWHY/3.png",
            "answer":"b"
        },
        {
            "id":"4",
            "question":"https://i.postimg.cc/fytG65yC/4.png",
            "answer":"b"
        },
        {
            "id":"5",
            "question":"https://i.postimg.cc/q7pdz8DB/5.png",
            "answer":"a"
        },
        {
            "id":"6",
            "question":"https://i.postimg.cc/KzHXqCG4/6.png",
            "answer":"c"
        },
        {
            "id":"7",
            "question":"https://i.postimg.cc/C11T4wVW/7.png",
            "answer":"a"
        },
        {
            "id":"8",
            "question":"https://i.postimg.cc/TPQvmpBV/8.png",
            "answer":"b"
        },
        {
            "id":"9",
            "question":"https://i.postimg.cc/Wbr3Zw80/9.png",
            "answer":"b"
        },
        {
            "id":"10",
            "question":"https://i.postimg.cc/Kj66FLg2/10.png",
            "answer":"a"
        },
        {
            "id":"11",
            "question":"https://i.postimg.cc/CMRdhgfP/11.png",
            "answer":"a"
        },
        {
            "id":"12",
            "question":"https://i.postimg.cc/3rzNWcXK/12.png",
            "answer":"d"
        },
        {
            "id":"13",
            "question":"https://i.postimg.cc/T3J372Zw/13.png",
            "answer":"d"
        },
        {
            "id":"14",
            "question":"https://i.postimg.cc/3xTwF0fV/14.png",
            "answer":"b"
        },
        {
            "id":"15",
            "question":"https://i.postimg.cc/6Q65DJXh/15.png",
            "answer":"a"
        },
        {
            "id":"16",
            "question":"https://i.postimg.cc/25H8YcjN/16.png",
            "answer":"b"
        },
        {
            "id":"17",
            "question":"https://i.postimg.cc/pTpVLfyh/17.png",
            "answer":"a"
        },
        {
            "id":"18",
            "question":"https://i.postimg.cc/7hzxgq3q/18.png",
            "answer":"b"
        },
        {
            "id":"19",
            "question":"https://i.postimg.cc/0QFkMzJt/19.png",
            "answer":"b"
        },
        {
            "id":"20",
            "question":"https://i.postimg.cc/Kc3vXDdC/20.png",
            "answer":"b"
        },
    ],
};

export default naeasy;