const namedium = {
    "name":"Network Analysis Signals and System",
    "questions": [

        {
            "id":"1",
            "question":"https://i.postimg.cc/rpPwP4BJ/21.png",
            "answer":"c"
        },
        {
            "id":"2",
            "question":"https://i.postimg.cc/3R0x5R7H/22.png",
            "answer":"a"
        },
        {
            "id":"3",
            "question":"https://i.postimg.cc/x8rT02TN/23.png",
            "answer":"a"
        },
        {
            "id":"4",
            "question":"https://i.postimg.cc/XqwNqzpH/24.png",
            "answer":"a"
        },
        {
            "id":"5",
            "question":"https://i.postimg.cc/0ytkzmys/25.png",
            "answer":"d"
        },
        {
            "id":"6",
            "question":"https://i.postimg.cc/qBnv1zjs/26.png",
            "answer":"b"
        },
        {
            "id":"7",
            "question":"https://i.postimg.cc/L6p6w2br/27.png",
            "answer":"c"
        },
        {
            "id":"8",
            "question":"https://i.postimg.cc/kXvXdLrD/28.png",
            "answer":"a"
        },
        {
            "id":"9",
            "question":"https://i.postimg.cc/cCMZ0tbP/29.png",
            "answer":"b"
        },
        {
            "id":"10",
            "question":"https://i.postimg.cc/pLVVVkxC/30.png",
            "answer":"a"
        },
        {
            "id":"11",
            "question":"https://i.postimg.cc/hG6KrBmZ/31.png",
            "answer":"d"
        },
        {
            "id":"12",
            "question":"https://i.postimg.cc/s2vV7XMZ/32.png",
            "answer":"b"
        },
        {
            "id":"13",
            "question":"https://i.postimg.cc/Qt7hYyk8/33.png",
            "answer":"b"
        },
        {
            "id":"14",
            "question":"https://i.postimg.cc/Vvc1xWDj/34.png",
            "answer":"c"
        },
        {
            "id":"15",
            "question":"https://i.postimg.cc/L4zmzG8v/35.png",
            "answer":"c"
        },
        {
            "id":"16",
            "question":"https://i.postimg.cc/dtwwnn7F/36.png",
            "answer":"d"
        },
        {
            "id":"17",
            "question":"https://i.postimg.cc/gksd7RRZ/37.png",
            "answer":"a"
        },
        {
            "id":"18",
            "question":"https://i.postimg.cc/437gnS06/38.png",
            "answer":"d"
        },
        {
            "id":"19",
            "question":"https://i.postimg.cc/CxKYp1H6/39.png",
            "answer":"c"
        },
        {
            "id":"20",
            "question":"https://i.postimg.cc/YCy7rHd2/40.png",
            "answer":"a"
        },
    ],
};

export default namedium;