const mathmedium = {
    "name":"Math",
    "questions": [

        {
            "id":"1",
            "question":"https://i.postimg.cc/XJ4P3104/20.png",
            "answer":"d"
        },
        {
            "id":"2",
            "question":"https://i.postimg.cc/8cCnfF5Y/21.png",
            "answer":"a"
        },
        {
            "id":"3",
            "question":"https://i.postimg.cc/W4MyBLC5/23.png",
            "answer":"d"
        },
        {
            "id":"4",
            "question":"https://i.postimg.cc/PqGcVr3L/24.png",
            "answer":"d"
        },
        {
            "id":"5",
            "question":"https://i.postimg.cc/rmjPpG8W/25.png",
            "answer":"c"
        },
        {
            "id":"6",
            "question":"https://i.postimg.cc/dtLxqTgk/26.png",
            "answer":"c"
        },
        {
            "id":"7",
            "question":"https://i.postimg.cc/wxWr8k4Y/27.png",
            "answer":"d"
        },
        {
            "id":"8",
            "question":"https://i.postimg.cc/fygqcwSR/28.png",
            "answer":"b"
        },
        {
            "id":"9",
            "question":"https://i.postimg.cc/wjN4NYq9/29.png",
            "answer":"c"
        },
        {
            "id":"10",
            "question":"https://i.postimg.cc/yNzQXpxc/30.png",
            "answer":"a"
        },
        {
            "id":"11",
            "question":"https://i.postimg.cc/7LMBB1Jc/31.png",
            "answer":"b"
        },
        {
            "id":"12",
            "question":"https://i.postimg.cc/rF3YzwLh/32.png",
            "answer":"c"
        },
        {
            "id":"13",
            "question":"https://i.postimg.cc/JnrpSybh/33.png",
            "answer":"c"
        },
        {
            "id":"14",
            "question":"https://i.postimg.cc/C5dmLWrT/46.png",
            "answer":"b"
        },
        {
            "id":"15",
            "question":"https://i.postimg.cc/xC66Q0R3/47.png",
            "answer":"b"
        },
        {
            "id":"16",
            "question":"https://i.postimg.cc/KjVQKJCK/48.png",
            "answer":"b"
        },
        {
            "id":"17",
            "question":"https://i.postimg.cc/gcBgB2rY/49.png",
            "answer":"a"
        },
        {
            "id":"18",
            "question":"https://i.postimg.cc/c4pX0kQ2/50.png",
            "answer":"b"
        },
        {
            "id":"19",
            "question":"https://i.postimg.cc/wjDFv52v/51.png",
            "answer":"a"
        },
        {
            "id":"20",
            "question":"https://i.postimg.cc/N0YDryCx/52.png",
            "answer":"c"
        },
    ],
};

export default mathmedium;