const mathhard = {
    "name":"Math",
    "questions": [

        {
            "id":"1",
            "question":"https://i.postimg.cc/Znb71wy2/1.png",
            "answer":"d"
        },
        {
            "id":"2",
            "question":"https://i.postimg.cc/Wp8fMcBv/2.png",
            "answer":"b"
        },
        {
            "id":"3",
            "question":"https://i.postimg.cc/vmnN9gsq/3.png",
            "answer":"c"
        },
        {
            "id":"4",
            "question":"https://i.postimg.cc/Y0dnkQ69/4.png",
            "answer":"d"
        },
        {
            "id":"5",
            "question":"https://i.postimg.cc/G2Jg7W9v/5.png",
            "answer":"c"
        },
        {
            "id":"6",
            "question":"https://i.postimg.cc/jd8mrYcX/6.png",
            "answer":"a"
        },
        {
            "id":"7",
            "question":"https://i.postimg.cc/26fXxkjz/7.png",
            "answer":"a"
        },
        {
            "id":"8",
            "question":"https://i.postimg.cc/bwW5s0KS/8.png",
            "answer":"c"
        },
        {
            "id":"9",
            "question":"https://i.postimg.cc/02rZDMGY/9.png",
            "answer":"b"
        },
        {
            "id":"10",
            "question":"https://i.postimg.cc/50xS06NF/10.png",
            "answer":"d"
        },
        {
            "id":"11",
            "question":"https://i.postimg.cc/63YLGtyb/11.png",
            "answer":"a"
        },
        {
            "id":"12",
            "question":"https://i.postimg.cc/ZqPL4rZS/12.png",
            "answer":"d"
        },
        {
            "id":"13",
            "question":"https://i.postimg.cc/2yydQMWk/13.png",
            "answer":"a"
        },
        {
            "id":"14",
            "question":"https://i.postimg.cc/Y0P6bRN1/14.png",
            "answer":"c"
        },
        {
            "id":"15",
            "question":"https://i.postimg.cc/WbD6hRjS/26.png",
            "answer":"b"
        },
        {
            "id":"16",
            "question":"https://i.postimg.cc/pXgQj0Lv/27.png",
            "answer":"a"
        },
        {
            "id":"17",
            "question":"https://i.postimg.cc/pVcJWVNp/28.png",
            "answer":"c"
        },
        {
            "id":"18",
            "question":"https://i.postimg.cc/Z5t3nCwK/29.png",
            "answer":"a"
        },
        {
            "id":"19",
            "question":"https://i.postimg.cc/gjLXkWRZ/30.png",
            "answer":"a"
        },
        {
            "id":"20",
            "question":"https://i.postimg.cc/mhxcP5N6/31.png",
            "answer":"a"
        },
    ],
};

export default mathhard;