const matheasy = {
    "name": "Math",
    "questions": [

        {
            "id":"1",
            "question":"https://i.postimg.cc/BnFHpqPw/1.png",
            "answer":"c"
        },
        {
            "id":"2",
            "question":"https://i.postimg.cc/GpJY0qQF/2.png",
            "answer":"c"
        },
        {
            "id":"3",
            "question":"https://i.postimg.cc/HscyWpzs/4.png",
            "answer":"b"
        },
        {
            "id":"4",
            "question":"https://i.postimg.cc/Fzqkbqr4/7.png",
            "answer":"c"
        },
        {
            "id":"5",
            "question":"https://i.postimg.cc/y6rRzJFb/9.png",
            "answer":"c"
        },
        {
            "id":"6",
            "question":"https://i.postimg.cc/QtfTCCvV/10.png",
            "answer":"c"
        },
        {
            "id":"7",
            "question":"https://i.postimg.cc/Hnj7yHCz/11.png",
            "answer":"b"
        },
        {
            "id":"8",
            "question":"https://i.postimg.cc/P51vZ20g/13.png",
            "answer":"c"
        },
        {
            "id":"9",
            "question":"https://i.postimg.cc/FsMJ72Cb/15.png",
            "answer":"a"
        },
        {
            "id":"10",
            "question":"https://i.postimg.cc/JhmDQjLG/16.png",
            "answer":"d"
        },
        {
            "id":"11",
            "question":"https://i.postimg.cc/76Z5FDb4/17.png",
            "answer":"c"
        },
        {
            "id":"12",
            "question":"https://i.postimg.cc/435K2nfw/18.png",
            "answer":"a"
        },
        {
            "id":"13",
            "question":"https://i.postimg.cc/8cFjCHhn/19.png",
            "answer":"c"
        },{
            "id":"14",
            "question":"https://i.postimg.cc/tJL7nxkR/20.png",
            "answer":"b"
        },
        {
            "id":"15",
            "question":"https://i.postimg.cc/C1rRYtfq/21.png",
            "answer":"a"
        },
        {
            "id":"16",
            "question":"https://i.postimg.cc/9XSDn623/22.png",
            "answer":"d"
        },
        {
            "id":"17",
            "question":"https://i.postimg.cc/c4nvyF1v/23.png",
            "answer":"a"
        },
        {
            "id":"18",
            "question":"https://i.postimg.cc/k5nGS9QS/24.png",
            "answer":"a"
        },
        {
            "id":"19",
            "question":"https://i.postimg.cc/FHb111Lm/25.png",
            "answer":"a"
        },
        {
            "id":"20",
            "question":"https://i.postimg.cc/sgCvV51w/26.png",
            "answer":"d"
        },
    ],
};

export default matheasy;